=== Azure/BatchExplorer/desktop/data/themes/theme.schema.json
{
  "title": "JSON schema for coffeelint.json files",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": true,
  "definitions": {
    "color": {"type": "string", "format": "color"},
    "entity-colors": {
      "type": "object",
      "properties": {
        "text": {"$ref": "#/definitions/color"},
        "background":{"$ref": "#/definitions/color"},
        "hover-text": {"$ref": "#/definitions/color"},
        "hover-background":{"$ref": "#/definitions/color"}
      }
    }
  },
  "properties": {
    "primary": {"$ref": "#/definitions/color"},
    "primary-contrast": {"$ref": "#/definitions/color"},
    "danger": {"$ref": "#/definitions/color"},
    "danger-contrast": {"$ref": "#/definitions/color"},
    "warn": {"$ref": "#/definitions/color"},
    "warn-contrast": {"$ref": "#/definitions/color"},
    "success": {"$ref": "#/definitions/color"},
    "success-contrast": {"$ref": "#/definitions/color"},
    "main-background": {"$ref": "#/definitions/color"},
    "secondary-background": {"$ref": "#/definitions/color"},
    "card-background": {"$ref": "#/definitions/color"},
    "hover-bg": {"$ref": "#/definitions/color"},
    "selection": {"$ref": "#/definitions/color"},
    "border": {"$ref": "#/definitions/color"},
    "outline": {"$ref": "#/definitions/color"},
    "editor": {"type": "string"},
    "text": {
      "type": "object",
      "properties": {
        "primary": {"$ref": "#/definitions/color"},
        "secondary": {"$ref": "#/definitions/color"}
      }
    },
    "header": {"$ref": "#/definitions/entity-colors"},
    "navigation": {"$ref": "#/definitions/entity-colors"},
    "footer": {"$ref": "#/definitions/entity-colors"},
    "breadcrumb": {"$ref": "#/definitions/entity-colors"},
    "file-explorer": {
      "type": "object",
      "properties": {
        "folder-icon": {"$ref": "#/definitions/color"}
      }
    },
    "button": {
      "type": "object",
      "properties": {
        "basic-text": {"$ref": "#/definitions/color"},
        "basic-bg": {"$ref": "#/definitions/color"},
        "basic-hover-bg": {"$ref": "#/definitions/color"},
        "disabled-text": {"$ref": "#/definitions/color"},
        "focus-text": {"$ref": "#/definitions/color"},
        "disabled-bg": {"$ref": "#/definitions/color"}
      }
    },
    "input": {
      "type": "object",
      "properties": {
        "text": {"$ref": "#/definitions/color"},
        "background": {"$ref": "#/definitions/color"},
        "placeholder": {"$ref": "#/definitions/color"},
        "border": {"$ref": "#/definitions/color"},
        "focus-border": {"$ref": "#/definitions/color"},
        "disabled-border": {"$ref": "#/definitions/color"},
        "disabled-text": {"$ref": "#/definitions/color"},
        "disabled-background": {"$ref": "#/definitions/color"}
      }
    },
    "chart-colors": {
      "type": "array",
      "items": {"$ref": "#/definitions/color"}
    }
  }
}

=== Azure/BatchExplorer/desktop/data/themes/dark.json
{
  "$schema": "./theme.schema.json",
  "primary": "#61afef",
  "danger": "#e06c75",
  "warn": "#f4ad42",
  "success": "#4caf50",
  "main-background": "#21252B",
  "secondary-background": "#333842",
  "card-background": "#282c34",
  "hover-bg": "#3d4148",
  "border": "#474a4f",
  "editor": "vs-dark",
  "text": {
    "primary": "#cccccc",
    "secondary": "#a7a8a9"
  },
  "breadcrumb": {
    "text": "white",
    "background": "#5b5b5b",
    "hover-background": "#666666"
  },
  "header": {
    "text": "#9da5b4",
    "background": "#333333",
    "hover-background": "#757575"
  },
  "navigation": {
    "text": "white",
    "background": "#333842",
    "hover-background": "#666666"
  },
  "footer": {
    "text": "whitesmoke",
    "background": "var(--color-primary)",
    "hover": "#757575"
  },
  "button": {
    "basic-text": "var(--color-primary)",
    "basic-bg": "#3F3F46",
    "basic-hover-bg": "#373744",
    "disabled-text": "#8B8B8B",
    "disabled-bg": "#2D2D30"
  },
  "input": {
    "border": "#3C4049",
    "focus-border": "var(--color-primary)",
    "placeholder": "#d5d5d5",
    "text": "var(--color-text-primary)",
    "background": "#21252B",
    "disabled-text": "var(--color-text-primary)",
    "disabled-border": "#3C4049",
    "disabled-background": "#2D2D30"
  }
}
